package com.adarsh.urlshortener.service;

import com.adarsh.urlshortener.dto.ShortenRequest;
import com.adarsh.urlshortener.dto.ShortenResponse;
import com.adarsh.urlshortener.entity.UrlMapping;
import com.adarsh.urlshortener.exception.AliasAlreadyExistsException;
import com.adarsh.urlshortener.exception.InvalidUrlException;
import com.adarsh.urlshortener.exception.NotFoundException;
import com.adarsh.urlshortener.repository.UrlRepository;
import com.adarsh.urlshortener.util.Base62;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;

import java.net.URI;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class UrlService {

    private final UrlRepository repository;

    @PersistenceContext
    private EntityManager entityManager;

    public ShortenResponse shorten(ShortenRequest request){

        validate(request.getUrl());

        var existing=repository.findByOriginalUrl(request.getUrl());

        if(existing.isPresent()){
            // If the code is temporary (being generated by another thread), wait for it to complete.
            int retries = 0;
            while (existing.isPresent() && existing.get().getShortCode().startsWith("TEMP_") && retries < 20) {
                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                entityManager.clear(); // Clear persistence context to bypass L1 cache
                existing = repository.findByOriginalUrl(request.getUrl());
                retries++;
            }
            if (existing.isPresent() && !existing.get().getShortCode().startsWith("TEMP_")) {
                return ShortenResponse.builder()
                        .code(existing.get().getShortCode())
                        .build();
            }
        }

        // Custom Alias Flow
        if(request.getAlias()!=null&&!request.getAlias().isBlank()){

            if(repository.existsByShortCode(request.getAlias())){
                throw new AliasAlreadyExistsException("Alias already exists");
            }

            UrlMapping mapping=UrlMapping.builder()
                    .originalUrl(request.getUrl())
                    .shortCode(request.getAlias())
                    .alias(request.getAlias())
                    .build();

            try {
                repository.saveAndFlush(mapping);
            } catch (DataIntegrityViolationException e) {
                // Check if alias was already taken concurrently
                if (repository.existsByShortCode(request.getAlias())) {
                    throw new AliasAlreadyExistsException("Alias already exists");
                }
                // Check if originalUrl was saved concurrently
                var concurrentExisting = repository.findByOriginalUrl(request.getUrl());
                int retries = 0;
                while (concurrentExisting.isPresent() && concurrentExisting.get().getShortCode().startsWith("TEMP_") && retries < 20) {
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Thread.currentThread().interrupt();
                    }
                    entityManager.clear();
                    concurrentExisting = repository.findByOriginalUrl(request.getUrl());
                    retries++;
                }
                return concurrentExisting
                        .map(m -> ShortenResponse.builder().code(m.getShortCode()).build())
                        .orElseThrow(() -> e);
            }

            return ShortenResponse.builder()
                    .code(mapping.getShortCode())
                    .build();
        }

        // Base62 Shortening Flow
        // To satisfy nullable=false and unique=true on shortCode during first save,
        // we use a temporary unique placeholder.
        UrlMapping mapping=UrlMapping.builder()
                .originalUrl(request.getUrl())
                .shortCode("TEMP_" + UUID.randomUUID())
                .build();

        try {
            mapping = repository.saveAndFlush(mapping);
        } catch (DataIntegrityViolationException e) {
            // Concurrent request already saved this originalUrl
            var concurrentExisting = repository.findByOriginalUrl(request.getUrl());
            int retries = 0;
            while (concurrentExisting.isPresent() && concurrentExisting.get().getShortCode().startsWith("TEMP_") && retries < 20) {
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                }
                entityManager.clear();
                concurrentExisting = repository.findByOriginalUrl(request.getUrl());
                retries++;
            }
            return concurrentExisting
                    .map(m -> ShortenResponse.builder().code(m.getShortCode()).build())
                    .orElseThrow(() -> e);
        }

        mapping.setShortCode(Base62.encode(mapping.getId()));

        repository.saveAndFlush(mapping);

        return ShortenResponse.builder()
                .code(mapping.getShortCode())
                .build();

    }

    public String getOriginalUrl(String code){

        return repository.findByShortCode(code)
                .orElseThrow(()->new NotFoundException("Code not found"))
                .getOriginalUrl();

    }

    private void validate(String url){

        try{

            URI uri=new URI(url);

            if(uri.getScheme()==null||uri.getHost()==null){
                throw new InvalidUrlException("Invalid URL");
            }

        }catch(Exception e){
            throw new InvalidUrlException("Invalid URL");
        }

    }

}
